config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :patients

end

app/models/patient.rb
class Patient < ActiveRecord::Base

  include Workflow
  workflow do
    state :waiting do
      event :go_to_doctor, transitions_to: :doctor
      event :go_to_xray, transitions_to: :xray
      event :go_to_surgery, transitions_to: :surgery
      event :go_to_leaving, transitions_to: :leaving
    end
    state :doctor do
      event :go_to_xray, transitions_to: :xray
      event :go_to_surgery, transitions_to: :surgery
      event :go_to_billpay, transitions_to: :billpay
    end
    state :xray do
      event :go_to_doctor, transitions_to: :doctor
      event :go_to_surgery, transitions_to: :surgery
      event :go_to_billpay, transitions_to: :billpay
    end
    state :surgery do
      event :go_to_doctor, transitions_to: :doctor
      event :go_to_xray, transitions_to: :xray
      event :go_to_billpay, transitions_to: :billpay
    end
    state :billpay do
      event :pay_bill, transitions_to: :leaving

    end       
    state :leaving
  end  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
  @patients = Patient.all
end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

def show
  @patient = Patient.find params[:id]
end

def new
  @patient = Patient.new
end

def create
  @patient = Patient.create patient_params
  redirect_to root_path
end

def edit
  @patient = Patient.find params[:id]
end

def update
  @patient = Patient.find params[:id]
  @patient.update_attributes patient_params
  redirect_to root_path
end

private
  def patient_params
    params.require(:patient).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/home/index.html.haml
%h4 Hospital Chris
=link_to 'New Patient', new_patient_path
%ul
  - @patients.each do |patient|
    %li
      =patient.name 
      =patient.description
      =link_to 'Show Patient', patient_path(patient)    
      =link_to 'Edit Patient', edit_patient_path(patient)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hospital</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/patients/_form.html.haml
= form_for @patient do |f|
  =f.label :name
  =f.text_field :name, placeholder: "Name"
  %br
  =f.label :description
  =f.text_area :description, placeholder: "Description"
  %br
  =f.submit 
%hr
= link_to "home", root_path

app/views/patients/edit.html.haml
%h3 Edit Patient
=render 'form'

app/views/patients/new.html.haml
%h4 Add a patient
= render 'form'

app/views/patients/show.html.haml
%h3 Patient Information
= @patient.name
%br
= @patient.description
%br
= link_to 'Home', root_path